/*
 * knowledge.h
 * autogenerated
*/

#ifndef STROKES_H_
#define STROKES_H_

#define DIMENTION 3
#define STROKE_MAX_LENGTH 256
#define SEGMENTATION 128
#define STROKES_COUNT 7
#define MIN_DIMENTION 1.0
#define ACCELERATION_TIME_CONST 0.2
#define GYRO_MIN 1000
#define GYRO_TIMEOUT 20
#define MIN_STROKE_LENGTH 20
#define COMPARE_LIMIT 1.5
#define CALIBRATION 0
#define IDLE 1
#define STATES_OFFSET 2

extern const float STROKES[STROKES_COUNT][SEGMENTATION][DIMENTION];
extern const float MAGNETS_BOUNDARIES[2][DIMENTION];


#endif
