/*
 * strokes.h
 * autogenerated
*/

#ifndef STROKES_H_
#define STROKES_H_

#define DIMENTION 3
#define SEGMENTATION 128
#define STROKES_COUNT 3
#define SEQUENCES_COUNT 2
#define NORMAL_SEQUENCE_LENGTH 2
#define STROKE_E5DE21F0 0 // circle down
#define STROKE_0F078BFA 1 // circle up
#define STROKE_1AE92ED9 2 // circle in front
#define STROKE_________ 3 // used, if the seq is shorter then NORMAL_SEQUENCE_LENGTH

#define INIT_STROKE STROKE_0F078BFA
#define SEQUENCE_0 0 // defence
#define SEQUENCE_1 1 // atack

extern int const SEQUENCES[SEQUENCES_COUNT][NORMAL_SEQUENCE_LENGTH];
extern float const STROKES[STROKES_COUNT][SEGMENTATION][DIMENTION + 1];


#endif
