#!/usr/bin/env python
# -*- coding: utf-8 -*-


from os.path import join
from os import walk

import numpy as np


if __name__ == '__main__':
    path = '../raw/source'
    for (dirpath, dirnames, filenames) in walk(path):
        if dirpath == path:
            continue
        for f in sorted(filenames):
            fullname = join(dirpath, f)
            try:
                data = np.loadtxt(fullname)
            except ValueError:
                continue
            data[:, 2] = -data[:, 2]
            np.savetxt(fullname, data)
